### ISSUE TITLE
Feature: Simulation of Linking Resources

### ISSUE THREAD

**Issue by klinakuf** [PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core#18]
- How does Simulizar/EventSim simulate and what is the intended semantic?

**Comment by stiesssh** [comment]
status (06.09.):
- with an FCFS that  simulated the linking resource
- on each ext. call. trigger a job for the linking resource

- changes to existing jobs (renames and more lovel of abstraction) because of assumptions made by existing jobs.

- open questions : how to calc demand? 
  * simulizar : calculate byte size from stack frame (for sarah : the size of the request!)
  * Request without parameters still has a size, and this is the demand we are searching for right now.

**Comment by stiesssh** [comment]
status (11.09.): 
* there's a bug, but it is already in fixing.
